import { ask, buyer, doc, group, input, line, opts, pack, supplier, yesno } from "./build";

const hse = [yesno("hse_policy", ["Do you have a documented HSE policy and management system?", "هل لديكم سياسة وإدارة موثقة للصحة والسلامة والبيئة؟"], "qualification"),
  ask("hse_record", ["Summarise your safety record for the last three years.", "لخصوا سجل السلامة لديكم خلال السنوات الثلاث الأخيرة."], "info")];

export const CONSTRUCTION = pack("CONSTRUCTION_PACK", [
  { key: "CON_WORKS_RFQ", type: "RFQ", category: "CONSTRUCTION_WORKS", title: ["Construction works RFQ (bill of quantities)", "طلب عرض سعر أعمال إنشائية (جدول كميات)"], summary: ["Price a bill of quantities for civil or fit-out works.", "تسعير جدول كميات لأعمال مدنية أو تشطيبات."], model: "itemized",
    fields: [buyer("site_location", "general", ["Site location", "موقع العمل"], "text", true), buyer("works_start", "general", ["Planned start date", "تاريخ البدء المخطط"], "date", false), supplier("programme_weeks", "mobilisation", ["Completion period (weeks)", "مدة الإنجاز (بالأسابيع)"], "integer", true), supplier("defects_months", "warranty", ["Defects liability period (months)", "فترة المسؤولية عن العيوب (بالأشهر)"], "integer", true)],
    questions: hse, documents: [doc("method_statement", ["Method statement", "بيان طريقة العمل"], ["How the works will be executed safely.", "كيف ستنفذ الأعمال بأمان."]), doc("trade_licence", ["Trade licence and classification", "الرخصة التجارية والتصنيف"], ["Shows you may do this type of work.", "تثبت أحقيتكم في هذا النوع من الأعمال."])] },
  { key: "CON_SUBCONTRACT_RFP", type: "RFP", category: "CONSTRUCTION_WORKS", title: ["Construction subcontract RFP (milestones)", "طلب عرض مقاول باطن (مراحل)"], summary: ["Proposal for a works package priced by milestone.", "مقترح لحزمة أعمال بتسعير حسب المراحل."], model: "milestone",
    fields: [buyer("site_location", "general", ["Site location", "موقع العمل"], "text", true), supplier("programme_weeks", "mobilisation", ["Completion period (weeks)", "مدة الإنجاز (بالأسابيع)"], "integer", true), supplier("retention_pct", "commercial", ["Retention you accept (%)", "نسبة الاستقطاع المقبولة (٪)"], "decimal", false, { envelope: "commercial" })],
    questions: [...hse, ask("resources", ["Describe the labour, plant and supervision you will assign.", "صفوا العمالة والمعدات والإشراف التي ستخصصونها."])],
    groups: [group("milestone", ["Milestone", "المرحلة"], [input("count", ["Number of identical stages", "عدد المراحل المتماثلة"], "integer", true, 1)])],
    lines: [line("milestone_price", ["Milestone: {name}", "المرحلة: {name}"], "count", "STAGE", "LUMP_SUM", { group: "milestone" })],
    documents: [doc("method_statement", ["Method statement", "بيان طريقة العمل"], ["How the works will be executed safely.", "كيف ستنفذ الأعمال بأمان."]), doc("programme", ["Construction programme", "البرنامج الزمني للتنفيذ"], ["Key dates and sequence.", "التواريخ الرئيسية والتسلسل."], ["pdf", "xlsx"])] },
]);

export const STAFFING = pack("STAFFING_PACK", [
  { key: "STF_MANPOWER_RFP", type: "RFP", category: "MANPOWER", title: ["Manpower supply RFP", "طلب عرض توريد عمالة"], summary: ["Supply of staff by role, priced per person per month with optional overtime.", "توريد عمالة حسب الدور بتسعير شهري للفرد مع عمل إضافي اختياري."], model: "manpower",
    fields: [buyer("work_location", "general", ["Work location", "موقع العمل"], "text", true), buyer("contract_months", "general", ["Contract duration (months)", "مدة العقد (بالأشهر)"], "integer", true), supplier("mobilisation_days", "mobilisation", ["Days to mobilise", "أيام التعبئة"], "integer", true)],
    questions: [yesno("labour_compliance", ["Do you confirm compliance with labour law, visas and insurance for all staff?", "هل تؤكدون الالتزام بقانون العمل والتأشيرات والتأمين لجميع العاملين؟"], "qualification"), ask("recruitment", ["Describe how you recruit, vet and replace staff.", "صفوا كيف تستقطبون العاملين وتتحققون منهم وتستبدلونهم."])],
    groups: [group("role", ["Role", "الدور"], [input("staff", ["Number of staff", "عدد العاملين"], "integer"), input("months", ["Months", "الأشهر"], "decimal"), input("overtime_hours", ["Expected overtime hours per person", "ساعات العمل الإضافي المتوقعة لكل فرد"], "decimal", false, 0)])],
    lines: [line("monthly", ["Monthly rate: {name}", "الأجر الشهري: {name}"], "staff * months", "MAN-MONTH", "UNIT_PRICE", { group: "role" }), line("overtime", ["Overtime hours: {name}", "ساعات العمل الإضافي: {name}"], "staff * overtime_hours", "HOUR", "UNIT_PRICE", { group: "role", when: "overtime_hours > 0" })],
    documents: [doc("licence", ["Manpower supply licence", "رخصة توريد العمالة"], ["Shows you may supply labour.", "تثبت أحقيتكم في توريد العمالة."])] },
  { key: "STF_PROFESSIONAL_RFQ", type: "RFQ", category: "MANPOWER", title: ["Professional resources RFQ (day rates)", "طلب عرض سعر موارد مهنية (أجور يومية)"], summary: ["Day rates for consultants or specialists.", "أجور يومية للاستشاريين أو المتخصصين."], model: "person_day",
    fields: [buyer("work_location", "general", ["Work location", "موقع العمل"], "text", false), supplier("availability_date", "mobilisation", ["Earliest start date", "أقرب تاريخ للبدء"], "date", true)],
    groups: [group("role", ["Role", "الدور"], [input("people", ["Number of people", "عدد الأشخاص"], "integer"), input("days", ["Days each", "الأيام لكل شخص"], "integer")])],
    lines: [line("day_rate", ["Day rate: {name}", "الأجر اليومي: {name}"], "people * days", "PERSON-DAY", "UNIT_PRICE", { group: "role" })],
    documents: [doc("cvs", ["Résumés of proposed people", "السير الذاتية للأشخاص المقترحين"], ["Experience of the people you propose.", "خبرة الأشخاص الذين تقترحونهم."], ["pdf", "docx"])] },
]);

export const FACILITIES = pack("FACILITIES_PACK", [
  { key: "FAC_SERVICES_RFP", type: "RFP", category: "FACILITIES_SERVICE", title: ["Integrated facilities services RFP", "طلب عرض خدمات مرافق متكاملة"], summary: ["Soft and hard services per building, priced as a monthly fee.", "خدمات مرافق لكل مبنى بتسعير رسم شهري."], model: "subscription",
    fields: [buyer("service_scope", "general", ["Services required", "الخدمات المطلوبة"], "multi", true, { options: opts(["cleaning", "Cleaning", "التنظيف"], ["hvac", "HVAC maintenance", "صيانة التكييف"], ["mep", "Electrical and plumbing", "الكهرباء والسباكة"], ["landscape", "Landscaping", "تنسيق الحدائق"], ["pest", "Pest control", "مكافحة الآفات"], ["security", "Security", "الأمن"]) }), buyer("response_hours", "general", ["Required response time for urgent calls (hours)", "زمن الاستجابة المطلوب للبلاغات العاجلة (بالساعات)"], "integer", false), supplier("onsite_team", "service", ["Team permanently on site", "الفريق الدائم في الموقع"], "text", true)],
    questions: [ask("service_plan", ["Describe how you will deliver and report on the services.", "صفوا كيف ستقدمون الخدمات وتعدون التقارير عنها."]), yesno("kpi_ok", ["Do you accept service levels with deductions for misses?", "هل تقبلون مستويات خدمة مع خصومات عند التقصير؟"], "info")],
    groups: [group("building", ["Building", "المبنى"], [input("months", ["Months", "الأشهر"], "integer", true, 12)])],
    lines: [line("fee", ["Monthly fee: {name}", "الرسم الشهري: {name}"], "months", "MONTH", "UNIT_PRICE", { group: "building" }), line("mobilisation", ["Mobilisation", "التعبئة"], "1", "LS", "LUMP_SUM", { optional: true })],
    documents: [doc("service_levels", ["Proposed service levels", "مستويات الخدمة المقترحة"], ["Response and resolution times.", "أزمنة الاستجابة والحل."])] },
  { key: "FAC_CLEANING_RFQ", type: "RFQ", category: "FACILITIES_SERVICE", title: ["Cleaning service RFQ", "طلب عرض سعر خدمات التنظيف"], summary: ["Cleaning priced per site per month.", "تنظيف بتسعير شهري لكل موقع."], model: "subscription",
    fields: [buyer("frequency", "general", ["Cleaning frequency", "تكرار التنظيف"], "single", true, { options: opts(["daily", "Daily", "يوميًا"], ["weekly", "Weekly", "أسبوعيًا"], ["custom", "As described", "كما هو موصوف"]) }), supplier("materials_included", "service", ["Are cleaning materials included?", "هل مواد التنظيف مشمولة؟"], "boolean", true)],
    groups: [group("site", ["Site", "الموقع"], [input("months", ["Months", "الأشهر"], "integer", true, 12)])],
    lines: [line("monthly", ["Monthly cleaning: {name}", "التنظيف الشهري: {name}"], "months", "MONTH", "UNIT_PRICE", { group: "site" })] },
]);

export const MANUFACTURING = pack("MANUFACTURING_PACK", [
  { key: "MFG_MATERIAL_RFQ", type: "RFQ", category: "RAW_MATERIAL", title: ["Raw material and components RFQ", "طلب عرض سعر مواد خام ومكونات"], summary: ["Materials and parts with origin, certificates and delivery terms.", "مواد وقطع مع المنشأ والشهادات وشروط التسليم."], model: "itemized", leadTime: true,
    fields: [buyer("delivery_terms", "general", ["Delivery terms wanted", "شروط التسليم المطلوبة"], "single", false, { options: opts(["exw", "Ex works", "تسليم المصنع"], ["fob", "FOB", "تسليم ظهر السفينة"], ["cif", "CIF", "التكلفة والتأمين والشحن"], ["ddp", "Delivered duty paid", "تسليم شامل الرسوم"]) }), supplier("country_of_origin", "equipment", ["Country of origin", "بلد المنشأ"], "text", true), supplier("moq", "equipment", ["Minimum order quantity", "الحد الأدنى لكمية الطلب"], "text", false), supplier("offered_terms", "mobilisation", ["Delivery terms offered", "شروط التسليم المعروضة"], "text", true)],
    documents: [doc("coa", ["Certificate of analysis or conformity", "شهادة التحليل أو المطابقة"], ["Shows the material meets the specification.", "تثبت أن المادة مطابقة للمواصفات."]), doc("datasheet", ["Technical datasheet", "الورقة الفنية"], ["Specification of the offered material.", "مواصفات المادة المعروضة."])] },
  { key: "MFG_COMPONENT_RFP", type: "RFP", category: "RAW_MATERIAL", title: ["Contract manufacturing RFP", "طلب عرض تصنيع تعاقدي"], summary: ["Proposal to manufacture to drawings, with optional tooling.", "مقترح للتصنيع وفق المخططات مع أدوات اختيارية."], model: "mixed", leadTime: true,
    fields: [buyer("annual_volume", "general", ["Expected annual volume", "الحجم السنوي المتوقع"], "text", false), supplier("capacity", "service", ["Monthly capacity you can reserve", "الطاقة الشهرية التي يمكنكم تخصيصها"], "text", true)],
    questions: [ask("quality_system", ["Describe your quality system and inspection of finished parts.", "صفوا نظام الجودة لديكم وفحص القطع النهائية."]), yesno("iso", ["Are you certified to a recognised quality standard such as ISO 9001?", "هل لديكم شهادة جودة معتمدة مثل ISO 9001؟"], "info")],
    lines: [line("tooling", ["Tooling and set-up", "الأدوات والتجهيز"], "1", "LS", "LUMP_SUM", { optional: true })],
    documents: [doc("quality_manual", ["Quality manual or certificates", "دليل الجودة أو الشهادات"], ["Evidence of your quality system.", "ما يثبت نظام الجودة لديكم."])] },
]);

export const OILGAS = pack("OILGAS_PACK", [
  { key: "OG_TURNAROUND_RFP", type: "RFP", category: "OIL_GAS_SERVICES", title: ["Shutdown or turnaround services RFP", "طلب عرض خدمات الصيانة الشاملة (التوقف)"], summary: ["Specialist crews for a plant shutdown, priced per role with HSE qualification.", "طواقم متخصصة لصيانة شاملة بتسعير حسب الدور مع تأهيل للسلامة."], model: "manpower",
    fields: [buyer("plant_site", "general", ["Plant or site", "المصنع أو الموقع"], "text", true), buyer("shutdown_days", "general", ["Planned shutdown duration (days)", "مدة التوقف المخطط (بالأيام)"], "integer", false), supplier("mobilisation_days", "mobilisation", ["Days to mobilise", "أيام التعبئة"], "integer", true)],
    questions: [...hse, yesno("permit_ok", ["Can your crews work under the site permit-to-work system?", "هل يمكن لطواقمكم العمل ضمن نظام تصاريح العمل بالموقع؟"], "qualification"), ask("crew_plan", ["Describe crew structure, supervision and competence evidence.", "صفوا هيكل الطاقم والإشراف وما يثبت الكفاءة."])],
    groups: [group("role", ["Role", "الدور"], [input("staff", ["Number of staff", "عدد العاملين"], "integer"), input("hours", ["Normal hours per person", "ساعات العمل العادية لكل فرد"], "decimal"), input("overtime_hours", ["Expected overtime hours per person", "ساعات العمل الإضافي المتوقعة لكل فرد"], "decimal", false, 0)])],
    lines: [line("normal", ["Normal hours: {name}", "الساعات العادية: {name}"], "staff * hours", "HOUR", "UNIT_PRICE", { group: "role" }), line("overtime", ["Overtime hours: {name}", "ساعات العمل الإضافي: {name}"], "staff * overtime_hours", "HOUR", "UNIT_PRICE", { group: "role", when: "overtime_hours > 0" }), line("mobilisation", ["Mobilisation and demobilisation", "التعبئة وفك التعبئة"], "1", "LS", "LUMP_SUM", { optional: true })],
    documents: [doc("competence", ["Competence and certification records", "سجلات الكفاءة والشهادات"], ["Certificates of the people you propose.", "شهادات الأشخاص الذين تقترحونهم."])] },
  { key: "OG_MRO_SUPPLY_RFQ", type: "RFQ", category: "OIL_GAS_MRO", title: ["MRO materials RFQ", "طلب عرض سعر مواد الصيانة والتشغيل"], summary: ["Spares and consumables with manufacturer, certificates and lead time.", "قطع غيار ومستهلكات مع المصنّع والشهادات ومدة التوريد."], model: "itemized", leadTime: true,
    fields: [buyer("delivery_site", "general", ["Delivery site", "موقع التسليم"], "text", true), supplier("manufacturer", "equipment", ["Manufacturer", "المصنّع"], "text", true), supplier("part_status", "equipment", ["Are the items new and original?", "هل الأصناف جديدة وأصلية؟"], "boolean", true), warrantyField()],
    documents: [doc("mtc", ["Material test certificates", "شهادات اختبار المواد"], ["Traceability for the supplied items.", "تتبع الأصناف الموردة."]), doc("datasheet", ["Technical datasheets", "الأوراق الفنية"], ["Specification of offered items.", "مواصفات الأصناف المعروضة."])] },
]);
function warrantyField() { return supplier("warranty_months", "warranty", ["Warranty period (months)", "مدة الضمان (بالأشهر)"], "integer", true); }

export const LOGISTICS = pack("LOGISTICS_PACK", [
  { key: "LOG_FREIGHT_RFQ", type: "RFQ", category: "FREIGHT", title: ["Freight lanes RFQ", "طلب عرض سعر مسارات شحن"], summary: ["Rates per shipping lane with expected volumes.", "أسعار لكل مسار شحن مع الأحجام المتوقعة."], model: "freight",
    fields: [buyer("cargo_type", "general", ["Cargo type", "نوع البضاعة"], "text", true), buyer("incoterms", "general", ["Incoterms", "شروط التسليم الدولية"], "text", false), supplier("transit_days", "service", ["Typical transit time (days)", "مدة العبور المعتادة (بالأيام)"], "integer", true), supplier("free_days", "commercial", ["Free days at destination", "الأيام المجانية في الوجهة"], "integer", false, { envelope: "commercial" })],
    groups: [group("lane", ["Lane (from – to)", "المسار (من – إلى)"], [input("shipments", ["Expected shipments", "الشحنات المتوقعة"], "integer")])],
    lines: [line("freight_rate", ["Freight rate: {name}", "سعر الشحن: {name}"], "shipments", "SHIPMENT", "UNIT_PRICE", { group: "lane" }), line("customs", ["Customs clearance: {name}", "التخليص الجمركي: {name}"], "shipments", "SHIPMENT", "UNIT_PRICE", { group: "lane", optional: true })],
    documents: [doc("insurance", ["Cargo insurance cover", "تغطية تأمين البضائع"], ["Shows the cover for goods in transit.", "تبين التغطية للبضائع أثناء النقل."])] },
  { key: "LOG_WAREHOUSING_RFP", type: "RFP", category: "WAREHOUSING", title: ["Warehousing and distribution RFP", "طلب عرض تخزين وتوزيع"], summary: ["Storage priced per pallet position per month, with handling.", "تخزين بتسعير لكل موقع طبلية شهريًا مع المناولة."], model: "subscription",
    fields: [buyer("storage_conditions", "general", ["Storage conditions", "ظروف التخزين"], "single", true, { options: opts(["ambient", "Ambient", "حرارة عادية"], ["chilled", "Chilled", "مبرد"], ["frozen", "Frozen", "مجمد"], ["hazmat", "Hazardous goods", "مواد خطرة"]) }), supplier("wms", "service", ["Inventory system and visibility offered", "نظام المخزون والرؤية المتاحة"], "text", true)],
    groups: [group("warehouse", ["Warehouse or zone", "المستودع أو المنطقة"], [input("pallets", ["Pallet positions", "مواقع الطبليات"], "integer"), input("months", ["Months", "الأشهر"], "integer", true, 12)])],
    lines: [line("storage", ["Storage: {name}", "التخزين: {name}"], "pallets * months", "PALLET-MONTH", "UNIT_PRICE", { group: "warehouse" }), line("handling", ["Handling in and out: {name}", "المناولة دخولًا وخروجًا: {name}"], "pallets", "PALLET", "UNIT_PRICE", { group: "warehouse", optional: true })],
    documents: [doc("facility", ["Facility description and licences", "وصف المنشأة والتراخيص"], ["Where goods will be stored and under which licence.", "أين ستُخزن البضائع وبموجب أي ترخيص."])] },
]);

export const HEALTHCARE = pack("HEALTHCARE_PACK", [
  { key: "HC_MEDICAL_EQUIPMENT_RFQ", type: "RFQ", category: "MEDICAL_EQUIPMENT", title: ["Medical equipment RFQ", "طلب عرض سعر معدات طبية"], summary: ["Equipment with regulatory registration, installation, training and warranty.", "معدات مع التسجيل التنظيمي والتركيب والتدريب والضمان."], model: "itemized", leadTime: true,
    fields: [buyer("delivery_site", "general", ["Delivery site (ward or department)", "موقع التسليم (القسم)"], "text", true), supplier("manufacturer", "equipment", ["Manufacturer and model", "المصنّع والطراز"], "text", true), supplier("registration_no", "equipment", ["Regulatory registration number", "رقم التسجيل التنظيمي"], "text", true), supplier("training_included", "service", ["Is user training included?", "هل التدريب للمستخدمين مشمول؟"], "boolean", true), warrantyField()],
    questions: [yesno("authorised", ["Are you the manufacturer or an authorised distributor in this country?", "هل أنتم المصنّع أو موزع معتمد في هذا البلد؟"], "qualification")],
    documents: [doc("registration", ["Regulatory approval or registration", "الموافقة التنظيمية أو التسجيل"], ["Shows the device may be used in this country.", "تثبت جواز استخدام الجهاز في هذا البلد."]), doc("datasheet", ["Datasheet and service manual", "الورقة الفنية ودليل الصيانة"], ["Specification and support information.", "المواصفات ومعلومات الدعم."])] },
  { key: "HC_CONSUMABLES_RFQ", type: "RFQ", category: "MEDICAL_EQUIPMENT", title: ["Medical consumables RFQ", "طلب عرض سعر مستهلكات طبية"], summary: ["Consumables with expiry dating, storage and batch traceability.", "مستهلكات مع تواريخ الصلاحية والتخزين وتتبع الدفعات."], model: "itemized", leadTime: true,
    fields: [buyer("min_expiry_months", "technical", ["Minimum remaining shelf life at delivery (months)", "الحد الأدنى لما تبقى من الصلاحية عند التسليم (بالأشهر)"], "integer", false), supplier("shelf_life_months", "equipment", ["Shelf life at delivery (months)", "الصلاحية عند التسليم (بالأشهر)"], "integer", true), supplier("storage_needs", "equipment", ["Storage requirements", "متطلبات التخزين"], "text", false)],
    questions: [yesno("batch_trace", ["Can you provide batch and expiry details with each delivery?", "هل يمكنكم تقديم تفاصيل الدفعة والصلاحية مع كل توريد؟"], "info")],
    documents: [doc("registration", ["Regulatory approval or registration", "الموافقة التنظيمية أو التسجيل"], ["Shows the product may be used in this country.", "تثبت جواز استخدام المنتج في هذا البلد."])] },
]);

export const IT = pack("IT_PACK", [
  { key: "IT_SOFTWARE_SUBSCRIPTION_RFP", type: "RFP", category: "IT_SOFTWARE", title: ["Software or cloud subscription RFP", "طلب عرض اشتراك برمجيات أو خدمة سحابية"], summary: ["Licences or cloud service priced per user per month, with security questions.", "تراخيص أو خدمة سحابية بتسعير للمستخدم شهريًا مع أسئلة أمنية."], model: "subscription",
    fields: [buyer("hosting_requirement", "general", ["Hosting requirement", "متطلب الاستضافة"], "single", false, { options: opts(["any", "No preference", "لا تفضيل"], ["in_country", "Data must stay in country", "يجب بقاء البيانات داخل الدولة"], ["on_prem", "On premises", "داخل المقر"]) }), supplier("hosting_location", "service", ["Where is the service hosted?", "أين تُستضاف الخدمة؟"], "text", true), supplier("uptime_pct", "service", ["Committed availability (%)", "نسبة الإتاحة الملتزم بها (٪)"], "decimal", true)],
    questions: [yesno("encryption", ["Is customer data encrypted in transit and at rest?", "هل تُشفَّر بيانات العميل أثناء النقل والتخزين؟"], "qualification"), yesno("exit", ["Can the customer export all of its data when the contract ends?", "هل يمكن للعميل تصدير كل بياناته عند انتهاء العقد؟"], "info"), ask("support_model", ["Describe support hours, channels and response times.", "صفوا ساعات الدعم وقنواته وأزمنة الاستجابة."])],
    groups: [group("licence", ["Licence or module", "الترخيص أو الوحدة"], [input("users", ["Users", "المستخدمون"], "integer"), input("months", ["Months", "الأشهر"], "integer", true, 12)])],
    lines: [line("subscription", ["Subscription: {name}", "الاشتراك: {name}"], "users * months", "USER-MONTH", "UNIT_PRICE", { group: "licence" }), line("onboarding", ["Onboarding and set-up", "الإعداد والتهيئة"], "1", "LS", "LUMP_SUM", { optional: true })],
    documents: [doc("security_evidence", ["Security certification or audit summary", "شهادة الأمن أو ملخص التدقيق"], ["Evidence of your security controls.", "ما يثبت ضوابط الأمن لديكم."]), doc("sla", ["Service level agreement", "اتفاقية مستوى الخدمة"], ["Availability and support commitments.", "التزامات الإتاحة والدعم."])] },
  { key: "IT_IMPLEMENTATION_RFP", type: "RFP", category: "IT_SOFTWARE", title: ["IT implementation services RFP", "طلب عرض خدمات تنفيذ تقنية"], summary: ["Implementation or development work priced in person-days by role.", "أعمال تنفيذ أو تطوير بتسعير أيام عمل حسب الدور."], model: "person_day",
    fields: [supplier("start_weeks", "mobilisation", ["Weeks until you can start", "الأسابيع حتى البدء"], "integer", true), supplier("delivery_method", "service", ["Delivery method", "منهجية التنفيذ"], "single", true, { options: opts(["agile", "Agile", "رشيقة"], ["waterfall", "Waterfall", "تتابعية"], ["hybrid", "Hybrid", "مختلطة"]) })],
    questions: [ask("team_plan", ["Describe the team, their roles and relevant experience.", "صفوا الفريق وأدواره وخبرته ذات الصلة."])],
    groups: [group("role", ["Role", "الدور"], [input("people", ["Number of people", "عدد الأشخاص"], "integer"), input("days", ["Days each", "الأيام لكل شخص"], "integer")])],
    lines: [line("day_rate", ["Day rate: {name}", "الأجر اليومي: {name}"], "people * days", "PERSON-DAY", "UNIT_PRICE", { group: "role" }), line("support_year", ["First-year support after go-live", "دعم السنة الأولى بعد التشغيل"], "1", "LS", "LUMP_SUM", { optional: true })],
    criteria: [["approach", "Approach and work plan", "الأسلوب وخطة العمل"], ["experience", "Experience and references", "الخبرة والمراجع"], ["team", "Team", "فريق العمل"]],
    documents: [doc("plan", ["Project plan", "خطة المشروع"], ["Milestones and dependencies.", "المراحل والاعتماديات."], ["pdf", "xlsx"])] },
]);
