// Writes supabase/migrations/0019_template_seed.sql from the typed packs. Run: npx vite-node scripts/gen-template-seed.ts
import { writeFileSync } from "node:fs";
import { PACKS_1, PACKS_2, TEMPLATES_1, TEMPLATES_2, TEMPLATES_3, type PackSeed } from "../src/templates/packs/index";
import type { TemplateSeed } from "../src/templates/types";
import { hashOf } from "../src/templates/resolve";

const q = (s: string) => "'" + s.replace(/'/g, "''") + "'";
const arr = (a: string[]) => `'{${a.map((x) => `"${x.replace(/"/g, '\\"')}"`).join(",")}}'`;
function gen(file: string, packs: PackSeed[], templates: TemplateSeed[], extra = "") {
  const out: string[] = ["-- GENERATED by scripts/gen-template-seed.ts from src/templates/packs. Do not edit by hand.", ""];
    if (extra) out.push(extra, "");
  for (const p of packs) out.push(`insert into industry_pack (code, label_en, label_ar, industry_codes) values (${q(p.code)}, ${q(p.en)}, ${q(p.ar)}, ${arr(p.industryCodes)});`);
  out.push("");
  for (const t of templates) {
    const m = t.meta;
    out.push(`insert into template_definition (key, kind, pack_code, category_code, event_type, method, pricing_model, title_en, title_ar, summary_en, summary_ar) values (${[m.key, m.kind, m.packCode, m.categoryCode, m.eventType, m.method, m.pricingModel, m.title.en, m.title.ar, m.summary.en, m.summary.ar].map((v) => (v === null ? "null" : q(v))).join(", ")});`);
  }
  out.push("");
  for (const t of templates) {
    out.push(`insert into template_version (template_key, version, schema_version, status, content, content_hash, requires, change_note, published_at) values (${q(t.meta.key)}, ${t.version}, 1, 'published', ${q(JSON.stringify(t.content))}::jsonb, ${q(hashOf(t.content))}, ${arr(t.meta.requires)}, ${q(t.changeNote)}, now());`);
  }
  writeFileSync(file, out.join("\n") + "\n");
    console.log("wrote", file, templates.length, "templates");
  }

gen("supabase/migrations/0019_template_seed.sql", PACKS_1, TEMPLATES_1);
gen("supabase/migrations/0020_template_packs_2.sql", PACKS_2, TEMPLATES_2, `insert into purchase_category (code, parent_code, label_en, label_ar, synonyms) values
 ('OIL_GAS_SERVICES','SERVICES','Oil and gas services','خدمات النفط والغاز','{"shutdown","turnaround","plant services"}'),
 ('OIL_GAS_MRO','GOODS','MRO materials and spares','مواد الصيانة والتشغيل وقطع الغيار','{"spares","consumables","mro"}'),
 ('WAREHOUSING','SERVICES','Warehousing and distribution','التخزين والتوزيع','{"storage","3pl"}');`);

{
  const out = ["-- GENERATED by scripts/gen-template-seed.ts from src/templates/packs/standard.ts. Do not edit by hand.", "-- Version 2 of every template. Companies upgrade when they choose; existing events are never changed.", ""];
  for (const t of TEMPLATES_3) out.push(`insert into template_version (template_key, version, schema_version, status, content, content_hash, requires, change_note, published_at) values (${q(t.meta.key)}, ${t.version}, 1, 'published', ${q(JSON.stringify(t.content))}::jsonb, ${q(hashOf(t.content))}, ${arr(t.meta.requires)}, ${q(t.changeNote)}, now()) on conflict (template_key, version) do nothing;`);
  writeFileSync("supabase/migrations/0027_templates_market_standard.sql", out.join("\n") + "\n");
  console.log("wrote 0027", TEMPLATES_3.length);
}
