// Writes supabase/migrations/0019_template_seed.sql from the typed packs. Run: npx vite-node scripts/gen-template-seed.ts
import { writeFileSync } from "node:fs";
import { ALL_TEMPLATES, PACKS } from "../src/templates/packs/index";
import { hashOf } from "../src/templates/resolve";

const q = (s: string) => "'" + s.replace(/'/g, "''") + "'";
const arr = (a: string[]) => `'{${a.map((x) => `"${x.replace(/"/g, '\\"')}"`).join(",")}}'`;
const out: string[] = ["-- GENERATED by scripts/gen-template-seed.ts from src/templates/packs. Do not edit by hand.", ""];
for (const p of PACKS) out.push(`insert into industry_pack (code, label_en, label_ar, industry_codes) values (${q(p.code)}, ${q(p.en)}, ${q(p.ar)}, ${arr(p.industryCodes)});`);
out.push("");
for (const t of ALL_TEMPLATES) {
  const m = t.meta;
  out.push(`insert into template_definition (key, kind, pack_code, category_code, event_type, method, pricing_model, title_en, title_ar, summary_en, summary_ar) values (${[m.key, m.kind, m.packCode, m.categoryCode, m.eventType, m.method, m.pricingModel, m.title.en, m.title.ar, m.summary.en, m.summary.ar].map((v) => (v === null ? "null" : q(v))).join(", ")});`);
}
out.push("");
for (const t of ALL_TEMPLATES) {
  out.push(`insert into template_version (template_key, version, schema_version, status, content, content_hash, requires, change_note, published_at) values (${q(t.meta.key)}, ${t.version}, 1, 'published', ${q(JSON.stringify(t.content))}::jsonb, ${q(hashOf(t.content))}, ${arr(t.meta.requires)}, ${q(t.changeNote)}, now());`);
}
writeFileSync("supabase/migrations/0019_template_seed.sql", out.join("\n") + "\n");
console.log("wrote", ALL_TEMPLATES.length, "templates");
